package eventplanner;
import java.sql.SQLException;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 */
public class addJobs extends javax.swing.JFrame {

    public addJobs() {
        initComponents();
    }

    public void addJobsClose(){
        this.setVisible(false);
    }
    
    public void addJobsOpen(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addJobsSubmitButton = new javax.swing.JButton();
        addJobBackButton = new javax.swing.JButton();
        addJobLabel = new javax.swing.JLabel();
        addJobTitleInput = new javax.swing.JTextField();
        addJobDatetimeInput = new javax.swing.JTextField();
        addJobTitleLabel = new javax.swing.JLabel();
        addJobDatetimeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addJobsSubmitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addJobsSubmitButton.setText("Submit");
        addJobsSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJobsSubmitButtonActionPerformed(evt);
            }
        });

        addJobBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addJobBackButton.setText("Back");

        addJobLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addJobLabel.setText("Add Job");

        addJobTitleInput.setToolTipText("");

        addJobTitleLabel.setText("Title:");

        addJobDatetimeLabel.setText("Date and Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(addJobsSubmitButton)
                        .addGap(31, 31, 31)
                        .addComponent(addJobBackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(addJobLabel)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addJobDatetimeLabel)
                    .addComponent(addJobTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addJobTitleInput, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(addJobDatetimeInput))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(addJobLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJobTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJobTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJobDatetimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJobDatetimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJobsSubmitButton)
                    .addComponent(addJobBackButton))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addJobsSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJobsSubmitButtonActionPerformed

        String jTitleIn = addJobTitleInput.getText();//getting the input for the job to be added to the database. -DC
        String jDatetimeIn = addJobDatetimeInput.getText();

        String addJobSQL = "INSERT into jobs(jTitle, jDatetime, eID) VALUES (\"" + jTitleIn + "\",\"" + jDatetimeIn + "\",\"" + dbWork.geteid() + "\")"; //building the sql query to pass to the worker. -DC
        
        try {
            dbWork.dbWorkAdd(dbWork.getLogin(), dbWork.getPassword(), addJobSQL);
            System.out.println("Job succesfully added."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
            addJobsClose(); //closing addJob Window. -DC
            viewJobs viewJobsUI = new viewJobs(); //Opening viewJob. -DC
            viewJobsUI.viewJobsOpen();
        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException");
        } catch (SQLException f) {
            System.out.println("SQLException");
        }

    }//GEN-LAST:event_addJobsSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addJobs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJobBackButton;
    private javax.swing.JTextField addJobDatetimeInput;
    private javax.swing.JLabel addJobDatetimeLabel;
    private javax.swing.JLabel addJobLabel;
    private javax.swing.JTextField addJobTitleInput;
    private javax.swing.JLabel addJobTitleLabel;
    private javax.swing.JButton addJobsSubmitButton;
    // End of variables declaration//GEN-END:variables
}
