/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventplanner;

import java.sql.SQLException;

/**
 *
 * @author Cooldev
 */
public class addSponsors extends javax.swing.JFrame {

    /**
     * Creates new form addSponsors
     */
    public addSponsors() {
        initComponents();
    }
    
    public void addSponsorsClose(){
        
        this.setVisible(false);
        
    }
    
    public void addSponsorsOpen(){
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSponsorLabel = new javax.swing.JLabel();
        addSponsorNameInput = new javax.swing.JTextField();
        addSponsorFnameInput = new javax.swing.JTextField();
        addSponsorNameLabel = new javax.swing.JLabel();
        addSponsorFnameLabel = new javax.swing.JLabel();
        addSponsorLnameInput = new javax.swing.JTextField();
        addSponsorLnameLabel = new javax.swing.JLabel();
        addSponsorPhoneLabel = new javax.swing.JLabel();
        addSponsorPhoneInput = new javax.swing.JTextField();
        addSponsorPledgeInput = new javax.swing.JTextField();
        addSponsorPledgeLabel = new javax.swing.JLabel();
        addSponsorSubmitButton = new javax.swing.JButton();
        addSponsorBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addSponsorLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addSponsorLabel.setText("Add Sponsor");

        addSponsorNameLabel.setText("Name of Sponsor:");

        addSponsorFnameLabel.setText("First Name:");

        addSponsorLnameLabel.setText("Last Name:");

        addSponsorPhoneLabel.setText("Phone:");

        addSponsorPledgeLabel.setText("Pledge:");

        addSponsorSubmitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addSponsorSubmitButton.setText("Submit");
        addSponsorSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSponsorSubmitButtonActionPerformed(evt);
            }
        });

        addSponsorBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addSponsorBackButton.setText("Back");
        addSponsorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSponsorBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(addSponsorSubmitButton)
                        .addGap(60, 60, 60)
                        .addComponent(addSponsorBackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addSponsorPledgeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addSponsorFnameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addSponsorLnameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addSponsorPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addSponsorNameLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addSponsorPledgeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(addSponsorLnameInput)
                                    .addComponent(addSponsorNameInput)
                                    .addComponent(addSponsorFnameInput)
                                    .addComponent(addSponsorPhoneInput))
                                .addGap(31, 31, 31))
                            .addComponent(addSponsorLabel))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addSponsorLabel)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSponsorNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorFnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSponsorFnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorLnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSponsorLnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorPhoneLabel)
                    .addComponent(addSponsorPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorPledgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSponsorPledgeLabel))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorSubmitButton)
                    .addComponent(addSponsorBackButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSponsorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSponsorBackButtonActionPerformed
        
        addSponsorsClose();// opening and closing UI windows to go back. -DC
        viewSponsors viewSponsorsUI = new viewSponsors();
        viewSponsorsUI.viewSponsorsOpen();
        
        
    }//GEN-LAST:event_addSponsorBackButtonActionPerformed

    private void addSponsorSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSponsorSubmitButtonActionPerformed
        //Submit addStaff event. Going to pass the field data to variables to be passed to the database. -DC
        String spFnameIn = addSponsorFnameInput.getText();
        String spLnameIn = addSponsorLnameInput.getText();
        String spNameIn = addSponsorNameInput.getText();
        String spPhoneIn = addSponsorPhoneInput.getText();
        String spPledgeIn = addSponsorPledgeInput.getText();
       
        

        String addSponsorSQL = "INSERT into sponsors(spName, spFname, spLname, spPhone, spPledge, eID) VALUES (\"" + spNameIn + "\",\"" + spFnameIn + "\",\"" + spLnameIn + "\",\"" + spPhoneIn + "\",\"" + spPledgeIn + "\",\"" + dbWork.geteid() + "\")";

        try {
            dbWork.dbWorkAdd(dbWork.getLogin(), dbWork.getPassword(), addSponsorSQL);
            System.out.println("Staff succesfully added."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
            addSponsorsClose(); //closing add staff Window. -DC
            viewSponsors viewSponsorsUI = new viewSponsors(); //Opening Staff Menu. -DC
            viewSponsorsUI.setVisible(true);
        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException");
        } catch (SQLException f) {
            System.out.println("SQLException");
        }
    }//GEN-LAST:event_addSponsorSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSponsors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSponsorBackButton;
    private javax.swing.JTextField addSponsorFnameInput;
    private javax.swing.JLabel addSponsorFnameLabel;
    private javax.swing.JLabel addSponsorLabel;
    private javax.swing.JTextField addSponsorLnameInput;
    private javax.swing.JLabel addSponsorLnameLabel;
    private javax.swing.JTextField addSponsorNameInput;
    private javax.swing.JLabel addSponsorNameLabel;
    private javax.swing.JTextField addSponsorPhoneInput;
    private javax.swing.JLabel addSponsorPhoneLabel;
    private javax.swing.JTextField addSponsorPledgeInput;
    private javax.swing.JLabel addSponsorPledgeLabel;
    private javax.swing.JButton addSponsorSubmitButton;
    // End of variables declaration//GEN-END:variables
}
