/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventplanner;

import java.sql.SQLException;

/**
 *
 * @author dmc02
 */
public class addStaff extends javax.swing.JFrame {

    /**
     * Creates new form addStaff
     */
    public addStaff() {
        initComponents();
    }
    
    public void addStaffClose(){ //closing method for addStaff. -DC
        
        this.setVisible(false);
        
    }
    
    public void addStaffOpen(){ //opening method for addStaff. -DC
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addStaffLabel = new javax.swing.JLabel();
        addStaffFirstNameInput = new javax.swing.JTextField();
        addStaffLastNameInput = new javax.swing.JTextField();
        addStaffPhoneInput = new javax.swing.JTextField();
        addStaffDatetimeInput = new javax.swing.JTextField();
        addStaffStatusInput = new javax.swing.JTextField();
        addStaffFirstNameLabel = new javax.swing.JLabel();
        addStaffLastNameLabel = new javax.swing.JLabel();
        addStaffPhoneLabel = new javax.swing.JLabel();
        addStaffDatetimeLabel = new javax.swing.JLabel();
        addStaffStatusLabel = new javax.swing.JLabel();
        addStaffSubmitButton = new javax.swing.JButton();
        addStaffBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addStaffLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addStaffLabel.setText("Add Staff");

        addStaffLastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffLastNameInputActionPerformed(evt);
            }
        });

        addStaffFirstNameLabel.setText("First Name:");

        addStaffLastNameLabel.setText("Last Name:");

        addStaffPhoneLabel.setText("Phone #:");

        addStaffDatetimeLabel.setText("Date and Time:");

        addStaffStatusLabel.setText("Status:");

        addStaffSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addStaffSubmitButton.setText("Submit");
        addStaffSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffSubmitButtonActionPerformed(evt);
            }
        });

        addStaffBackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addStaffBackButton.setText("Back");
        addStaffBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(addStaffLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(107, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addStaffFirstNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addStaffDatetimeLabel)
                                .addComponent(addStaffPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addStaffLastNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addStaffSubmitButton))
                            .addComponent(addStaffStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addStaffPhoneInput)
                            .addComponent(addStaffDatetimeInput)
                            .addComponent(addStaffLastNameInput)
                            .addComponent(addStaffFirstNameInput)
                            .addComponent(addStaffStatusInput, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(addStaffBackButton)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addStaffLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffFirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStaffFirstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStaffLastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStaffPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffDatetimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStaffDatetimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffStatusInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStaffStatusLabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStaffSubmitButton)
                    .addComponent(addStaffBackButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffBackButtonActionPerformed

        addStaffClose();
        viewStaff viewStaffUI = new viewStaff();
        viewStaffUI.viewStaffOpen();

        // TODO add your handling code here:
    }//GEN-LAST:event_addStaffBackButtonActionPerformed

    private void addStaffSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffSubmitButtonActionPerformed

//Submit addStaff event. Going to pass the field data to variables to be passed to the database. -DC
        String sFnameIn = addStaffFirstNameInput.getText();
        String sLnameIn = addStaffLastNameInput.getText();
        String sPhoneIn = addStaffPhoneInput.getText();
        String sDatetimeIn = addStaffDatetimeInput.getText();
        String sStatusIn = addStaffStatusInput.getText();
       
        

        String addStaffSQL = "INSERT into staff(sFname, sLname, sPhone, sDatetime, sStatus, eID) VALUES (\"" + sFnameIn + "\",\"" + sLnameIn + "\",\"" + sPhoneIn + "\",\"" + sDatetimeIn + "\",\"" + sStatusIn + "\",\"" + dbWork.geteid() + "\")";

        try {
            dbWork.dbWorkAdd(dbWork.getLogin(), dbWork.getPassword(), addStaffSQL);
            System.out.println("Staff succesfully added."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
            addStaffClose(); //closing add staff Window. -DC
            viewStaff viewStaffUI = new viewStaff(); //Opening Staff Menu. -DC
            viewStaffUI.setVisible(true);
        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException");
        } catch (SQLException f) {
            System.out.println("SQLException");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_addStaffSubmitButtonActionPerformed

    private void addStaffLastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffLastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStaffLastNameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffBackButton;
    private javax.swing.JTextField addStaffDatetimeInput;
    private javax.swing.JLabel addStaffDatetimeLabel;
    private javax.swing.JTextField addStaffFirstNameInput;
    private javax.swing.JLabel addStaffFirstNameLabel;
    private javax.swing.JLabel addStaffLabel;
    private javax.swing.JTextField addStaffLastNameInput;
    private javax.swing.JLabel addStaffLastNameLabel;
    private javax.swing.JTextField addStaffPhoneInput;
    private javax.swing.JLabel addStaffPhoneLabel;
    private javax.swing.JTextField addStaffStatusInput;
    private javax.swing.JLabel addStaffStatusLabel;
    private javax.swing.JButton addStaffSubmitButton;
    // End of variables declaration//GEN-END:variables
}
