package eventplanner;
import java.sql.SQLException;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 */
public class addSponsors extends javax.swing.JFrame {

    public addSponsors() {
        initComponents();
    }
    
    public void addSponsorsClose(){
        
        this.setVisible(false);
        
    }
    
    public void addSponsorsOpen(){
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addSponsorLogoLabel = new javax.swing.JLabel();
        addSponsorLabel = new javax.swing.JLabel();
        addSponsorNameInput = new javax.swing.JTextField();
        addSponsorNameLabel = new javax.swing.JLabel();
        addSponsorFnameInput = new javax.swing.JTextField();
        addSponsorFnameLabel = new javax.swing.JLabel();
        addSponsorLnameInput = new javax.swing.JTextField();
        addSponsorLnameLabel = new javax.swing.JLabel();
        addSponsorPhoneInput = new javax.swing.JTextField();
        addSponsorPhoneLabel = new javax.swing.JLabel();
        addSponsorPledgeInput = new javax.swing.JTextField();
        addSponsorPledgeLabel = new javax.swing.JLabel();
        addSponsorBackButton = new javax.swing.JButton();
        addSponsorSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addSponsorLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventplanner/horizonlogoTiny.png"))); // NOI18N

        addSponsorLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        addSponsorLabel.setText("Add Sponsor");

        addSponsorNameLabel.setText("Name of Sponsor:");

        addSponsorFnameLabel.setText("First Name:");

        addSponsorLnameLabel.setText("Last Name:");

        addSponsorPhoneLabel.setText("Phone:");

        addSponsorPledgeLabel.setText("Pledge:");

        addSponsorBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addSponsorBackButton.setText("Back");
        addSponsorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSponsorBackButtonActionPerformed(evt);
            }
        });

        addSponsorSubmitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addSponsorSubmitButton.setText("Submit");
        addSponsorSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSponsorSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(addSponsorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addSponsorLogoLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addSponsorNameLabel)
                                    .addComponent(addSponsorFnameLabel)
                                    .addComponent(addSponsorLnameLabel)
                                    .addComponent(addSponsorPhoneLabel)
                                    .addComponent(addSponsorPledgeLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addSponsorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addSponsorFnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addSponsorLnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addSponsorPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addSponsorPledgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(addSponsorSubmitButton)
                                .addGap(33, 33, 33)
                                .addComponent(addSponsorBackButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addSponsorLogoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(addSponsorLabel)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSponsorNameLabel)
                            .addComponent(addSponsorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSponsorFnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addSponsorFnameLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorLnameLabel)
                    .addComponent(addSponsorLnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSponsorPhoneLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorPledgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSponsorPledgeLabel))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSponsorSubmitButton)
                    .addComponent(addSponsorBackButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSponsorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSponsorBackButtonActionPerformed
        
        addSponsorsClose();// opening and closing UI windows to go back. -DC
        viewSponsors viewSponsorsUI = new viewSponsors();
        viewSponsorsUI.viewSponsorsOpen();
        
        
    }//GEN-LAST:event_addSponsorBackButtonActionPerformed

    private void addSponsorSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSponsorSubmitButtonActionPerformed
        //Submit Sponsor information. Going to pass the field data to variables to be passed to the database. -DC
        String spFnameIn = addSponsorFnameInput.getText();
        String spLnameIn = addSponsorLnameInput.getText();
        String spNameIn = addSponsorNameInput.getText();
        String spPhoneIn = addSponsorPhoneInput.getText();
        String spPledgeIn = addSponsorPledgeInput.getText();
      
        String addSponsorSQL = "INSERT into sponsors(spName, spFname, spLname, spPhone, spPledge, eID) VALUES (\"" + spNameIn + "\",\"" + spFnameIn + "\",\"" + spLnameIn + "\",\"" + spPhoneIn + "\",\"" + spPledgeIn + "\",\"" + dbWork.geteid() + "\")";

        try {
            dbWork.dbWorkAdd(dbWork.getLogin(), dbWork.getPassword(), addSponsorSQL);
            System.out.println("Staff succesfully added."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
            addSponsorsClose(); //closing add staff Window. -DC
            viewSponsors viewSponsorsUI = new viewSponsors(); //Opening viewSponsors Menu. -DC
            viewSponsorsUI.setVisible(true);
        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException");
        } catch (SQLException f) {
            System.out.println("SQLException");
        }
    }//GEN-LAST:event_addSponsorSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addSponsors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSponsorBackButton;
    private javax.swing.JTextField addSponsorFnameInput;
    private javax.swing.JLabel addSponsorFnameLabel;
    private javax.swing.JLabel addSponsorLabel;
    private javax.swing.JTextField addSponsorLnameInput;
    private javax.swing.JLabel addSponsorLnameLabel;
    private javax.swing.JLabel addSponsorLogoLabel;
    private javax.swing.JTextField addSponsorNameInput;
    private javax.swing.JLabel addSponsorNameLabel;
    private javax.swing.JTextField addSponsorPhoneInput;
    private javax.swing.JLabel addSponsorPhoneLabel;
    private javax.swing.JTextField addSponsorPledgeInput;
    private javax.swing.JLabel addSponsorPledgeLabel;
    private javax.swing.JButton addSponsorSubmitButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
