package eventplanner;
import java.sql.*;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 */
public class createEvent extends javax.swing.JFrame {
    /**
     * Creates new form createEvent
     */
    public createEvent() {
        initComponents();
    }

    public void createEventClose() { //setting Create Event Menu visiblity. -DC

        this.setVisible(false);

    }

    public void createEventOpen() { //setting Create Event Menu visiblity. -DC

        this.setVisible(true);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventNameLabel = new javax.swing.JLabel();
        eventLocationLabel = new javax.swing.JLabel();
        eventDatetimeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eventNameInput = new javax.swing.JTextField();
        eventLocationInput = new javax.swing.JTextField();
        eventDatetimeInput = new javax.swing.JTextField();
        eventSizeInput = new javax.swing.JTextField();
        createEventMenuLabel = new javax.swing.JLabel();
        createEventSubmitButton = new javax.swing.JButton();
        createEventBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eventNameLabel.setText("Event Name:");

        eventLocationLabel.setText("Event Location:");

        eventDatetimeLabel.setText("Event Dates and Time:");

        jLabel1.setText("Event Size:");

        createEventMenuLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        createEventMenuLabel.setText("Create Event");

        createEventSubmitButton.setText("Submit");
        createEventSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventSubmitButtonActionPerformed(evt);
            }
        });

        createEventBackButton.setText("Back");
        createEventBackButton.setToolTipText("");
        createEventBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createEventSubmitButton)
                        .addGap(35, 35, 35)
                        .addComponent(createEventBackButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(eventDatetimeLabel)
                            .addComponent(eventLocationLabel)
                            .addComponent(eventNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eventNameInput)
                            .addComponent(eventLocationInput)
                            .addComponent(eventDatetimeInput)
                            .addComponent(eventSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(createEventMenuLabel)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(createEventMenuLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventNameLabel)
                    .addComponent(eventNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventLocationLabel)
                    .addComponent(eventLocationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDatetimeLabel)
                    .addComponent(eventDatetimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eventSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEventSubmitButton)
                    .addComponent(createEventBackButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createEventBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventBackButtonActionPerformed

        createEventClose();
        eventMenu eventMenuGUI = new eventMenu();
        eventMenuGUI.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_createEventBackButtonActionPerformed

    private void createEventSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventSubmitButtonActionPerformed

//Submit Event Information. Going to pass the field data to variables to be passed to the database. -DC
        String eNameIn = eventNameInput.getText();
        String eLocationIn = eventLocationInput.getText();
        String eDatetimeIn = eventDatetimeInput.getText();
        String eSizeIn = eventSizeInput.getText();
        int sValue = Integer.parseInt(eSizeIn); //converting to integer for database input. -DC

        String createEventSQL = "INSERT into horizonevent(eName, eLocation, eDatetime, eSize) VALUES (\"" + eNameIn + "\",\"" + eLocationIn + "\",\"" + eDatetimeIn + "\",\"" + sValue + "\")";

        try {
            dbWork.dbWorkAdd(dbWork.getLogin(), dbWork.getPassword(), createEventSQL);
            System.out.println("Event succesfully added."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
            createEventClose(); //closing createEvent. -DC
            eventMenu eventMenuGUI = new eventMenu(); //Opening eventMenu. -DC
            eventMenuGUI.setVisible(true);
        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException");
        } catch (SQLException f) {
            System.out.println("SQLException");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_createEventSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEventBackButton;
    private javax.swing.JLabel createEventMenuLabel;
    private javax.swing.JButton createEventSubmitButton;
    private javax.swing.JTextField eventDatetimeInput;
    private javax.swing.JLabel eventDatetimeLabel;
    private javax.swing.JTextField eventLocationInput;
    private javax.swing.JLabel eventLocationLabel;
    private javax.swing.JTextField eventNameInput;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JTextField eventSizeInput;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
