package eventplanner;
import java.sql.*;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jvnet.substance.*;
import org.jvnet.substance.border.*;
import org.jvnet.substance.button.*;
import org.jvnet.substance.painter.*;
import org.jvnet.substance.theme.*;
import org.jvnet.substance.title.*;
import org.jvnet.substance.watermark.*;
/**
 *
 * @author Donovan Cummins - (Team Horizon
 * @UI developer Zilin Li - (Team Horizon)
 */
public class createEvent extends javax.swing.JFrame {
    /**
     * Creates new form createEvent
     */
    public createEvent() {
        initComponents();
    }

    public void createEventClose() { //setting Create Event Menu visiblity. -DC

        this.setVisible(false);

    }

    public void createEventOpen() { //setting Create Event Menu visiblity. -DC

        this.setVisible(true);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createEventLogoLabel = new javax.swing.JLabel();
        createEventMenuLabel = new javax.swing.JLabel();
        eventNameInput = new javax.swing.JTextField();
        eventNameLabel = new javax.swing.JLabel();
        eventLocationLabel = new javax.swing.JLabel();
        eventLocationInput = new javax.swing.JTextField();
        eventDatetimeLabel = new javax.swing.JLabel();
        eventDatetimeInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        eventSizeInput = new javax.swing.JTextField();
        createEventSubmitButton = new javax.swing.JButton();
        createEventBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        createEventLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventplanner/horizonlogoTiny.png"))); // NOI18N

        createEventMenuLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        createEventMenuLabel.setText("Create Event");

        eventNameLabel.setText("Event Name:");

        eventLocationLabel.setText("Event Location:");

        eventDatetimeLabel.setText("Event Dates and Time:");

        jLabel1.setText("Event Size:");

        createEventSubmitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        createEventSubmitButton.setText("Submit");
        createEventSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventSubmitButtonActionPerformed(evt);
            }
        });

        createEventBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        createEventBackButton.setText("Back");
        createEventBackButton.setToolTipText("");
        createEventBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(eventDatetimeLabel)
                            .addComponent(eventLocationLabel)
                            .addComponent(eventNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eventNameInput)
                            .addComponent(eventLocationInput)
                            .addComponent(eventDatetimeInput)
                            .addComponent(eventSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createEventSubmitButton)
                                .addGap(49, 49, 49)
                                .addComponent(createEventBackButton))
                            .addComponent(createEventMenuLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(createEventLogoLabel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(createEventLogoLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createEventMenuLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventNameLabel)
                    .addComponent(eventNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventLocationLabel)
                    .addComponent(eventLocationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventDatetimeLabel)
                    .addComponent(eventDatetimeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eventSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEventSubmitButton)
                    .addComponent(createEventBackButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createEventBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventBackButtonActionPerformed

        createEventClose();
        eventMenu eventMenuGUI = new eventMenu();
        eventMenuGUI.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_createEventBackButtonActionPerformed

    private void createEventSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventSubmitButtonActionPerformed

//Submit Event Information. Going to pass the field data to variables to be passed to the database. -DC
        String eNameIn = eventNameInput.getText();
        String eLocationIn = eventLocationInput.getText();
        String eDatetimeIn = eventDatetimeInput.getText();
        String eSizeIn = eventSizeInput.getText();
        int sValue = Integer.parseInt(eSizeIn); //converting to integer for database input. -DC

        String createEventSQL = "INSERT into horizonevent(eName, eLocation, eDatetime, eSize) VALUES (\"" + eNameIn + "\",\"" + eLocationIn + "\",\"" + eDatetimeIn + "\",\"" + sValue + "\")";

        try {
            dbWork.dbWorkAdd(dbWork.getLogin(), dbWork.getPassword(), createEventSQL);
            System.out.println("Event succesfully added."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
            createEventClose(); //closing createEvent. -DC
            eventMenu eventMenuGUI = new eventMenu(); //Opening eventMenu. -DC
            eventMenuGUI.setVisible(true);
        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException");
        } catch (SQLException f) {
            System.out.println("SQLException");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_createEventSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {  
            
        UIManager.setLookAndFeel(new SubstanceLookAndFeel());  
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.AutumnSkin");
        SubstanceLookAndFeel.setCurrentTheme(new org.jvnet.substance.theme.SubstanceBrownTheme());//Set theme. -ZL
         SubstanceLookAndFeel.setCurrentButtonShaper(new StandardButtonShaper()); 
                               SubstanceLookAndFeel.setCurrentWatermark(new SubstanceNoneWatermark());  // Set watermark. -ZL
                               
                               SubstanceLookAndFeel.setCurrentBorderPainter(new org.jvnet.substance.border.ClassicInnerBorderPainter());  //Set border. -ZL
 
                               SubstanceLookAndFeel.setCurrentGradientPainter(new StandardGradientPainter());  //Render Settings. -ZL  
                             
                               SubstanceLookAndFeel.setCurrentTitlePainter(new MatteHeaderPainter()); //Set title. -ZL
  
    } catch (UnsupportedLookAndFeelException e) {  
        System.err.println("Something went wrong!");  
    }  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEventBackButton;
    private javax.swing.JLabel createEventLogoLabel;
    private javax.swing.JLabel createEventMenuLabel;
    private javax.swing.JButton createEventSubmitButton;
    private javax.swing.JTextField eventDatetimeInput;
    private javax.swing.JLabel eventDatetimeLabel;
    private javax.swing.JTextField eventLocationInput;
    private javax.swing.JLabel eventLocationLabel;
    private javax.swing.JTextField eventNameInput;
    private javax.swing.JLabel eventNameLabel;
    private javax.swing.JTextField eventSizeInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
