package eventplanner;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jvnet.substance.*;
import org.jvnet.substance.border.*;
import org.jvnet.substance.button.*;
import org.jvnet.substance.painter.*;
import org.jvnet.substance.theme.*;
import org.jvnet.substance.title.*;
import org.jvnet.substance.watermark.*;

/**
 *
 * @author Donovan Cummins - (Team Horizon)
 * @UI developer Zilin Li - (Team Horizon)
 */
public class manageEvents extends javax.swing.JFrame {
    /**
     * Creates new form manageEvents
     */
    public manageEvents() {
        initComponents();
    }

    public void manageEventsClose(){
        this.setVisible(false);
    }
    
    public void manageEventsOpen(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        manageEventPanel = new javax.swing.JPanel();
        manageEventsLogoLabel = new javax.swing.JLabel();
        manageEventsViewButton = new javax.swing.JButton();
        manageEventsBackButton = new javax.swing.JButton();
        manageEventsJlist = new javax.swing.JScrollPane();
        manageEventJlist = new javax.swing.JList<>();
        manageEventsLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageEventPanel.setBackground(new java.awt.Color(255, 255, 255));

        manageEventsLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventplanner/horizonlogoTiny.png"))); // NOI18N

        manageEventsViewButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageEventsViewButton.setText("View");
        manageEventsViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEventsViewButtonActionPerformed(evt);
            }
        });

        manageEventsBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageEventsBackButton.setText("Back");
        manageEventsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEventsBackButtonActionPerformed(evt);
            }
        });

        manageEventJlist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        manageEventJlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Vendors", "Staff", "Jobs", "Sponsors" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        manageEventsJlist.setViewportView(manageEventJlist);

        manageEventsLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        manageEventsLabel.setText("Manage Event");

        javax.swing.GroupLayout manageEventPanelLayout = new javax.swing.GroupLayout(manageEventPanel);
        manageEventPanel.setLayout(manageEventPanelLayout);
        manageEventPanelLayout.setHorizontalGroup(
            manageEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEventPanelLayout.createSequentialGroup()
                .addGroup(manageEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageEventPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(manageEventsLabel))
                    .addGroup(manageEventPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(manageEventsJlist, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(manageEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageEventsViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEventsBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(manageEventsLogoLabel)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        manageEventPanelLayout.setVerticalGroup(
            manageEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageEventsLabel)
                .addGap(60, 60, 60)
                .addGroup(manageEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageEventPanelLayout.createSequentialGroup()
                        .addComponent(manageEventsLogoLabel)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageEventPanelLayout.createSequentialGroup()
                        .addGroup(manageEventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageEventsJlist, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(manageEventPanelLayout.createSequentialGroup()
                                .addComponent(manageEventsViewButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manageEventsBackButton)))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageEventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageEventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageEventsViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEventsViewButtonActionPerformed

    int eventChild = manageEventJlist.getSelectedIndex(); //User selects one of four choices and this is the index value of that selection. -DC
    
    /*
    Vendors = 0
    Staff = 1
    Jobs = 2
    Sponsors = 3
    */
    
    if(eventChild <= 0){
        //Use Case 8 and Use Case 9: AddVendor:RemoveVendor -DC
        
        manageEventsClose();
        viewVendor viewVendorUI = new viewVendor();
        viewVendorUI.viewVendorOpen();
        System.out.println("View Vendors");
        
    }else if(eventChild <= 1){
        //Use Case 4 and Use Case 5: AddStaff:RemoveStaff -DC
        
        manageEventsClose(); //User selected staff. Closing the manage window, opening the view staff window. -DC
        viewStaff viewStaffUI = new viewStaff();
        viewStaffUI.viewStaffOpen();
        System.out.println("View Staff");    
        
    }else if(eventChild <= 2){
        //Use Case 6 and Use Case 7: AddJob:RemoveJob -DC
        
        manageEventsClose(); //closing the manage UI and opening the appropriate child UI. -DC
        viewJobs viewJobsUI = new viewJobs();
        viewJobsUI.viewJobsOpen();        
        System.out.println("View Jobs");
        
    }else if(eventChild <= 3) {
        //Use Case 8 and Use Case 9: AddSponsor:RemoveSponsor -DC
        
        manageEventsClose();
        viewSponsors viewSponsorsUI = new viewSponsors();
        viewSponsorsUI.viewSponsorsOpen();
        System.out.println("View Sponsors");
        
    }
    
     
    }//GEN-LAST:event_manageEventsViewButtonActionPerformed

    private void manageEventsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEventsBackButtonActionPerformed

        manageEventsClose(); //back button. just flipping visiblility between ui objects. -DC
        viewEvents viewEventsUI = new viewEvents();
        viewEventsUI.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_manageEventsBackButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {  
            
        UIManager.setLookAndFeel(new SubstanceLookAndFeel());  
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.AutumnSkin");
        SubstanceLookAndFeel.setCurrentTheme(new org.jvnet.substance.theme.SubstanceBottleGreenTheme());//Set theme. -ZL
         SubstanceLookAndFeel.setCurrentButtonShaper(new StandardButtonShaper()); 
                               SubstanceLookAndFeel.setCurrentWatermark(new SubstanceNoneWatermark());  // Set watermark. -ZL
                               
                               SubstanceLookAndFeel.setCurrentBorderPainter(new org.jvnet.substance.border.ClassicInnerBorderPainter());  //Set border. -ZL
 
                               SubstanceLookAndFeel.setCurrentGradientPainter(new StandardGradientPainter());  //Render Settings. -ZL  
                             
                               SubstanceLookAndFeel.setCurrentTitlePainter(new MatteHeaderPainter()); //Set title. -ZL
  
    } catch (UnsupportedLookAndFeelException e) {  
        System.err.println("Something went wrong!");  
    }  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageEvents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> manageEventJlist;
    private javax.swing.JPanel manageEventPanel;
    private javax.swing.JButton manageEventsBackButton;
    private javax.swing.JScrollPane manageEventsJlist;
    private javax.swing.JLabel manageEventsLabel;
    private javax.swing.JLabel manageEventsLogoLabel;
    private javax.swing.JButton manageEventsViewButton;
    // End of variables declaration//GEN-END:variables
}
