package eventplanner;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jvnet.substance.*;
import org.jvnet.substance.border.*;
import org.jvnet.substance.button.*;
import org.jvnet.substance.painter.*;
import org.jvnet.substance.theme.*;
import org.jvnet.substance.title.*;
import org.jvnet.substance.watermark.*;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 * @UI developer Zilin Li - (Team Horizon)
 */
public class viewVendor extends javax.swing.JFrame {
   
    public viewVendor() {
        initComponents();
        
        try { //this is my way of populating the vendor list box with only the staff for the event the user selected. -DC
            
            DefaultListModel vendorList = dbWork.dbWorkSelectVendor(
                            dbWork.getLogin(), 
                            dbWork.getPassword(), 
                            "SELECT * FROM vendors where eID =" + 
                            dbWork.geteid() + 
                            "");//using defaultListModel to return the data of interest from the resultset. -DC
           
            viewVendorJlist.setModel(vendorList); //populating the listbox with data in the defaultListModel. -DC
            
            System.out.println("Vendors added to the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC

        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException viewVendor"); //Gotta catch'em all! -DC
        } catch (SQLException f) {//If at first you do not succeed... -DC
            System.out.println("SQLException viewVendor ");//Blame it on your SQL Syntax. -DC
        }
        
    }

    public void viewVendorClose(){
        this.setVisible(false);
    }
    
    public void viewVendorOpen(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewVendorPanel = new javax.swing.JPanel();
        viewVendorLogoLabel = new javax.swing.JLabel();
        viewVendorLabel = new javax.swing.JLabel();
        viewVendorBackButton = new javax.swing.JButton();
        viewVendorDeleteButton = new javax.swing.JButton();
        viewVendorAddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewVendorJlist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewVendorPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewVendorLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventplanner/horizonlogoTiny.png"))); // NOI18N

        viewVendorLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        viewVendorLabel.setText("View Vendor");

        viewVendorBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewVendorBackButton.setText("Back");
        viewVendorBackButton.setToolTipText("");
        viewVendorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorBackButtonActionPerformed(evt);
            }
        });

        viewVendorDeleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewVendorDeleteButton.setText("Delete");
        viewVendorDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorDeleteButtonActionPerformed(evt);
            }
        });

        viewVendorAddButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewVendorAddButton.setText("Add");
        viewVendorAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorAddButtonActionPerformed(evt);
            }
        });

        viewVendorJlist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewVendorJlist.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(viewVendorJlist);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel1.setText("Vendor Name");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel4.setText("Medium");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel5.setText("Status");

        javax.swing.GroupLayout viewVendorPanelLayout = new javax.swing.GroupLayout(viewVendorPanel);
        viewVendorPanel.setLayout(viewVendorPanelLayout);
        viewVendorPanelLayout.setHorizontalGroup(
            viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewVendorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewVendorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewVendorLabel)
                            .addGroup(viewVendorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel5))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewVendorPanelLayout.createSequentialGroup()
                        .addComponent(viewVendorLogoLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewVendorPanelLayout.createSequentialGroup()
                        .addGroup(viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewVendorDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewVendorAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewVendorBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        viewVendorPanelLayout.setVerticalGroup(
            viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewVendorPanelLayout.createSequentialGroup()
                .addComponent(viewVendorLogoLabel)
                .addGap(86, 86, 86)
                .addComponent(viewVendorAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewVendorDeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewVendorBackButton)
                .addGap(78, 78, 78))
            .addGroup(viewVendorPanelLayout.createSequentialGroup()
                .addComponent(viewVendorLabel)
                .addGap(20, 20, 20)
                .addGroup(viewVendorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewVendorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewVendorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewVendorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorBackButtonActionPerformed

        viewVendorClose(); //closing the viewVendor window and opening the manage events window. -DC
        manageEvents manageEventsUI = new manageEvents();
        manageEventsUI.manageEventsOpen();

    }//GEN-LAST:event_viewVendorBackButtonActionPerformed

    private void viewVendorDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorDeleteButtonActionPerformed

        int j = viewVendorJlist.getSelectedIndex(); //passing the selected index value to use to reference the right value in the dbWork vendorID arraylist. -DC
        System.out.println(j);
       

        try { //Try Catch for the dbWorkDeleteVendor method. Passing selected index at the time delete is pressed and passing the delete command to the database. -DC
            dbWork.dbWorkDeleteVendor(dbWork.getLogin(), dbWork.getPassword(), dbWork.getVID(j));
           
        } catch (ClassNotFoundException e) {
            System.out.println("ClassNotFoundException during vendorDelete.");
        } catch (SQLException f) {
            System.out.println("SQLException during vendorDelete.");
        }

        try {

            //using defaultListModel to return the data of interest from the resultset. -DC
            DefaultListModel vendorList = dbWork.dbWorkSelectVendor(
                            dbWork.getLogin(), 
                            dbWork.getPassword(), 
                            "SELECT * FROM vendors where eID =" + 
                            dbWork.geteid() + 
                            "");

            //populating the listbox with data in the defaultListModel. -DC
            viewVendorJlist.setModel(vendorList);
            
            System.out.println("Staff deleted from the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC

        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException viewVendors"); //Gotta catch'em all! -DC
        } catch (SQLException f) {//If at first you do not succeed... -DC
            System.out.println("SQLException viewVendors");//Blame it on your SQL Syntax. -DC
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_viewVendorDeleteButtonActionPerformed

    private void viewVendorAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorAddButtonActionPerformed

        viewVendorClose(); //closing current window and opening the add staff window. -DC
        addVendor addVendorUI = new addVendor();
        addVendorUI.addVendorOpen();

    }//GEN-LAST:event_viewVendorAddButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {  
            
        UIManager.setLookAndFeel(new SubstanceLookAndFeel());  
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.AutumnSkin");
        SubstanceLookAndFeel.setCurrentTheme(new org.jvnet.substance.theme.SubstanceBottleGreenTheme());//Set theme. -ZL
         SubstanceLookAndFeel.setCurrentButtonShaper(new StandardButtonShaper()); 
                               SubstanceLookAndFeel.setCurrentWatermark(new SubstanceNoneWatermark());  // Set watermark. -ZL
                               
                               SubstanceLookAndFeel.setCurrentBorderPainter(new org.jvnet.substance.border.ClassicInnerBorderPainter());  //Set border. -ZL
 
                               SubstanceLookAndFeel.setCurrentGradientPainter(new StandardGradientPainter());  //Render Settings. -ZL  
                             
                               SubstanceLookAndFeel.setCurrentTitlePainter(new MatteHeaderPainter()); //Set title. -ZL
  
    } catch (UnsupportedLookAndFeelException e) {  
        System.err.println("Something went wrong!");  
    }  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewVendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewVendorAddButton;
    private javax.swing.JButton viewVendorBackButton;
    private javax.swing.JButton viewVendorDeleteButton;
    private javax.swing.JList<String> viewVendorJlist;
    private javax.swing.JLabel viewVendorLabel;
    private javax.swing.JLabel viewVendorLogoLabel;
    private javax.swing.JPanel viewVendorPanel;
    // End of variables declaration//GEN-END:variables
}
