package eventplanner;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 */
public class viewSponsors extends javax.swing.JFrame {
    /**
     * Creates new form viewSponsors
     */
    public viewSponsors() {
        initComponents();
        
        try { //this is my way of populating the staff list box with only the staff for the event the user selected. -DC
            
            //using defaultListModel to return the data of interest from the resultset. -DC
            DefaultListModel sponsorsList = dbWork.dbWorkSelectSponsors(dbWork.getLogin(), dbWork.getPassword(), "SELECT * FROM sponsors where eID =" + dbWork.geteid() + "");
           
            viewSponsorsJlist.setModel(sponsorsList); //populating the listbox with data in the defaultListModel. -DC
            
            System.out.println("Events added to the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC

        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException viewSponsors"); //Gotta catch'em all! -DC
        } catch (SQLException f) {//If at first you do not succeed... -DC
            System.out.println("SQLException viewSponsors");//Blame it on your SQL Syntax. -DC
        }
        
    }
    
    public void viewSponsorsClose(){
        
        this.setVisible(false);
        
    }
    
    public void viewSponsorsOpen(){
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSponsorsBackButton = new javax.swing.JButton();
        viewSponsorsAddButton = new javax.swing.JButton();
        viewSponsorsDeleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewSponsorsJlist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewSponsorsBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewSponsorsBackButton.setText("Back");
        viewSponsorsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorsBackButtonActionPerformed(evt);
            }
        });

        viewSponsorsAddButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewSponsorsAddButton.setText("Add");
        viewSponsorsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorsAddButtonActionPerformed(evt);
            }
        });

        viewSponsorsDeleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewSponsorsDeleteButton.setText("Delete");
        viewSponsorsDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorsDeleteButtonActionPerformed(evt);
            }
        });

        viewSponsorsJlist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(viewSponsorsJlist);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("View Sponsors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSponsorsAddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSponsorsDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewSponsorsBackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewSponsorsAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSponsorsDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSponsorsBackButton)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSponsorsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorsBackButtonActionPerformed

        viewSponsorsClose();
        manageEvents manageEventsUI = new manageEvents();
        manageEventsUI.manageEventsOpen();

        
    }//GEN-LAST:event_viewSponsorsBackButtonActionPerformed

    private void viewSponsorsDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorsDeleteButtonActionPerformed
        
        int j = viewSponsorsJlist.getSelectedIndex(); //passing the selected index value to use to reference the right value in the dbWork sponsorsID arraylist. -DC
        System.out.println(j);       

        try { //Try Catch for the dbWorkDeleteSponsors method. Passing selected index at the time delete is pressed and passing the delete command to the database. -DC
            dbWork.dbWorkDeleteSponsor(dbWork.getLogin(), dbWork.getPassword(), dbWork.getSPID(j));           
        } catch (ClassNotFoundException e) {
            System.out.println("ClassNotFoundException sponsorDelete.");
        } catch (SQLException f) {
            System.out.println("SQLException sponsorDelete.");
        }

        try {
            
            //using defaultListModel to return the data of interest from the resultset. -DC
            DefaultListModel sponsorsList = dbWork.dbWorkSelectSponsors(
                            dbWork.getLogin(), 
                            dbWork.getPassword(), 
                            "SELECT * FROM sponsors where eID =" + 
                            dbWork.geteid() + 
                            "");
            
            viewSponsorsJlist.setModel(sponsorsList);//populating the listbox with data in the defaultListModel. -DC           
            System.out.println("Sponsors deleted from the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
        } catch (ClassNotFoundException e) { //Catching Errors. -DC            
            System.out.println("ClassNotFoundException viewSponsors"); //Gotta catch'em all! -DC            
        } catch (SQLException f) {//If at first you do not succeed... -DC            
            System.out.println("SQLException viewSponsors");//Blame it on your SQL Syntax. -DC            
        }
    }//GEN-LAST:event_viewSponsorsDeleteButtonActionPerformed

    private void viewSponsorsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorsAddButtonActionPerformed

        viewSponsorsClose();
        addSponsors addSponsorsUI = new addSponsors();
        addSponsorsUI.addSponsorsOpen();
        
    }//GEN-LAST:event_viewSponsorsAddButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSponsors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewSponsorsAddButton;
    private javax.swing.JButton viewSponsorsBackButton;
    private javax.swing.JButton viewSponsorsDeleteButton;
    private javax.swing.JList<String> viewSponsorsJlist;
    // End of variables declaration//GEN-END:variables
}
