package eventplanner;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 */
public class viewVendor extends javax.swing.JFrame {
   
    public viewVendor() {
        initComponents();
        
        try { //this is my way of populating the vendor list box with only the staff for the event the user selected. -DC
            
            DefaultListModel vendorList = dbWork.dbWorkSelectVendor(
                            dbWork.getLogin(), 
                            dbWork.getPassword(), 
                            "SELECT * FROM vendors where eID =" + 
                            dbWork.geteid() + 
                            "");//using defaultListModel to return the data of interest from the resultset. -DC
           
            viewVendorJlist.setModel(vendorList); //populating the listbox with data in the defaultListModel. -DC
            
            System.out.println("Vendors added to the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC

        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException viewVendor"); //Gotta catch'em all! -DC
        } catch (SQLException f) {//If at first you do not succeed... -DC
            System.out.println("SQLException viewVendor ");//Blame it on your SQL Syntax. -DC
        }
        
    }

    public void viewVendorClose(){
        this.setVisible(false);
    }
    
    public void viewVendorOpen(){
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewVendorJlist = new javax.swing.JList<>();
        viewVendorLabel = new javax.swing.JLabel();
        viewVendorBackButton = new javax.swing.JButton();
        viewVendorDeleteButton = new javax.swing.JButton();
        viewVendorAddButton = new javax.swing.JButton();
        viewVendorLogoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewVendorJlist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(viewVendorJlist);

        viewVendorLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        viewVendorLabel.setText("View Vendor");

        viewVendorBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewVendorBackButton.setText("Back");
        viewVendorBackButton.setToolTipText("");
        viewVendorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorBackButtonActionPerformed(evt);
            }
        });

        viewVendorDeleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewVendorDeleteButton.setText("Delete");
        viewVendorDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorDeleteButtonActionPerformed(evt);
            }
        });

        viewVendorAddButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewVendorAddButton.setText("Add");
        viewVendorAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVendorAddButtonActionPerformed(evt);
            }
        });

        viewVendorLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventplanner/horizonlogoTiny.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewVendorLabel)
                        .addGap(145, 145, 145)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewVendorBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewVendorDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewVendorAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewVendorLogoLabel)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(viewVendorLogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewVendorAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewVendorDeleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewVendorBackButton)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(viewVendorLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewVendorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorBackButtonActionPerformed

        viewVendorClose(); //closing the viewVendor window and opening the manage events window. -DC
        manageEvents manageEventsUI = new manageEvents();
        manageEventsUI.manageEventsOpen();

    }//GEN-LAST:event_viewVendorBackButtonActionPerformed

    private void viewVendorDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorDeleteButtonActionPerformed

        int j = viewVendorJlist.getSelectedIndex(); //passing the selected index value to use to reference the right value in the dbWork vendorID arraylist. -DC
        System.out.println(j);
       

        try { //Try Catch for the dbWorkDeleteVendor method. Passing selected index at the time delete is pressed and passing the delete command to the database. -DC
            dbWork.dbWorkDeleteVendor(dbWork.getLogin(), dbWork.getPassword(), dbWork.getVID(j));
           
        } catch (ClassNotFoundException e) {
            System.out.println("ClassNotFoundException during vendorDelete.");
        } catch (SQLException f) {
            System.out.println("SQLException during vendorDelete.");
        }

        try {

            //using defaultListModel to return the data of interest from the resultset. -DC
            DefaultListModel vendorList = dbWork.dbWorkSelectVendor(
                            dbWork.getLogin(), 
                            dbWork.getPassword(), 
                            "SELECT * FROM vendors where eID =" + 
                            dbWork.geteid() + 
                            "");

            //populating the listbox with data in the defaultListModel. -DC
            viewVendorJlist.setModel(vendorList);
            
            System.out.println("Staff deleted from the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC

        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException viewVendors"); //Gotta catch'em all! -DC
        } catch (SQLException f) {//If at first you do not succeed... -DC
            System.out.println("SQLException viewVendors");//Blame it on your SQL Syntax. -DC
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_viewVendorDeleteButtonActionPerformed

    private void viewVendorAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVendorAddButtonActionPerformed

        viewVendorClose(); //closing current window and opening the add staff window. -DC
        addVendor addVendorUI = new addVendor();
        addVendorUI.addVendorOpen();

    }//GEN-LAST:event_viewVendorAddButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewVendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewVendorAddButton;
    private javax.swing.JButton viewVendorBackButton;
    private javax.swing.JButton viewVendorDeleteButton;
    private javax.swing.JList<String> viewVendorJlist;
    private javax.swing.JLabel viewVendorLabel;
    private javax.swing.JLabel viewVendorLogoLabel;
    // End of variables declaration//GEN-END:variables
}
