package eventplanner;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jvnet.substance.*;
import org.jvnet.substance.border.*;
import org.jvnet.substance.button.*;
import org.jvnet.substance.painter.*;
import org.jvnet.substance.theme.*;
import org.jvnet.substance.title.*;
import org.jvnet.substance.watermark.*;
/**
 *
 * @author Donovan Cummins - (Team Horizon)
 * @UI developer Zilin Li - (Team Horizon)
 */
public class viewSponsors extends javax.swing.JFrame {
    /**
     * Creates new form viewSponsors
     */
    public viewSponsors() {
        initComponents();
        this.setLocationRelativeTo(null); //Professor Chen pointed this out during the demo, So I fixed it. -DC
        
        try { //this is my way of populating the staff list box with only the staff for the event the user selected. -DC
            
            //using defaultListModel to return the data of interest from the resultset. -DC
            DefaultListModel sponsorsList = dbWork.dbWorkSelectSponsors(dbWork.getLogin(), dbWork.getPassword(), "SELECT * FROM sponsors where eID =" + dbWork.geteid() + "");
           
            viewSponsorsJlist.setModel(sponsorsList); //populating the listbox with data in the defaultListModel. -DC
            
            System.out.println("Events added to the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC

        } catch (ClassNotFoundException e) { //Catching Errors. -DC
            System.out.println("ClassNotFoundException viewSponsors"); //Gotta catch'em all! -DC
        } catch (SQLException f) {//If at first you do not succeed... -DC
            System.out.println("SQLException viewSponsors");//Blame it on your SQL Syntax. -DC
        }
        
    }
    
    public void viewSponsorsClose(){
        
        this.setVisible(false);
        
    }
    
    public void viewSponsorsOpen(){
        
        this.setVisible(true);
        this.setLocationRelativeTo(null); //Professor Chen pointed this out during the demo, So I fixed it. -DC
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewSponsorsJlist = new javax.swing.JList<>();
        viewSponsorsLogoLabel = new javax.swing.JLabel();
        viewSponsorsAddButton = new javax.swing.JButton();
        viewSponsorsDeleteButton = new javax.swing.JButton();
        viewSponsorsBackButton = new javax.swing.JButton();
        viewSponsorsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        viewSponsorsJlist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewSponsorsJlist.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(viewSponsorsJlist);

        viewSponsorsLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventplanner/horizonlogoTiny.png"))); // NOI18N

        viewSponsorsAddButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewSponsorsAddButton.setText("Add");
        viewSponsorsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorsAddButtonActionPerformed(evt);
            }
        });

        viewSponsorsDeleteButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewSponsorsDeleteButton.setText("Delete");
        viewSponsorsDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorsDeleteButtonActionPerformed(evt);
            }
        });

        viewSponsorsBackButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        viewSponsorsBackButton.setText("Back");
        viewSponsorsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSponsorsBackButtonActionPerformed(evt);
            }
        });

        viewSponsorsLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        viewSponsorsLabel.setText("View Sponsors");

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel1.setText("Sponsor Name");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel4.setText("Phone");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel5.setText("Pledge");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewSponsorsLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel5)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewSponsorsDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewSponsorsAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewSponsorsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(viewSponsorsLogoLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewSponsorsLogoLabel)
                        .addGap(144, 144, 144)
                        .addComponent(viewSponsorsAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSponsorsDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSponsorsBackButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(viewSponsorsLabel)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSponsorsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorsBackButtonActionPerformed

        viewSponsorsClose();
        manageEvents manageEventsUI = new manageEvents();
        manageEventsUI.manageEventsOpen();

        
    }//GEN-LAST:event_viewSponsorsBackButtonActionPerformed

    private void viewSponsorsDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorsDeleteButtonActionPerformed
        
        int j = viewSponsorsJlist.getSelectedIndex(); //passing the selected index value to use to reference the right value in the dbWork sponsorsID arraylist. -DC
        System.out.println(j);       

        try { //Try Catch for the dbWorkDeleteSponsors method. Passing selected index at the time delete is pressed and passing the delete command to the database. -DC
            dbWork.dbWorkDeleteSponsor(dbWork.getLogin(), dbWork.getPassword(), dbWork.getSPID(j));           
        } catch (ClassNotFoundException e) {
            System.out.println("ClassNotFoundException sponsorDelete.");
        } catch (SQLException f) {
            System.out.println("SQLException sponsorDelete.");
        }

        try {
            
            //using defaultListModel to return the data of interest from the resultset. -DC
            DefaultListModel sponsorsList = dbWork.dbWorkSelectSponsors(
                            dbWork.getLogin(), 
                            dbWork.getPassword(), 
                            "SELECT * FROM sponsors where eID =" + 
                            dbWork.geteid() + 
                            "");
            
            viewSponsorsJlist.setModel(sponsorsList);//populating the listbox with data in the defaultListModel. -DC           
            System.out.println("Sponsors deleted from the list."); //Stub feedback. Followed by copy and pasted back button code for the same object. -DC
        } catch (ClassNotFoundException e) { //Catching Errors. -DC            
            System.out.println("ClassNotFoundException viewSponsors"); //Gotta catch'em all! -DC            
        } catch (SQLException f) {//If at first you do not succeed... -DC            
            System.out.println("SQLException viewSponsors");//Blame it on your SQL Syntax. -DC            
        }
    }//GEN-LAST:event_viewSponsorsDeleteButtonActionPerformed

    private void viewSponsorsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSponsorsAddButtonActionPerformed

        viewSponsorsClose();
        addSponsors addSponsorsUI = new addSponsors();
        addSponsorsUI.addSponsorsOpen();
        
    }//GEN-LAST:event_viewSponsorsAddButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSponsors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {  
            
        UIManager.setLookAndFeel(new SubstanceLookAndFeel());  
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.AutumnSkin");
        SubstanceLookAndFeel.setCurrentTheme(new org.jvnet.substance.theme.SubstanceBottleGreenTheme());//Set theme. -ZL
         SubstanceLookAndFeel.setCurrentButtonShaper(new StandardButtonShaper()); 
                               SubstanceLookAndFeel.setCurrentWatermark(new SubstanceNoneWatermark());  // Set watermark. -ZL
                               
                               SubstanceLookAndFeel.setCurrentBorderPainter(new org.jvnet.substance.border.ClassicInnerBorderPainter());  //Set border. -ZL
 
                               SubstanceLookAndFeel.setCurrentGradientPainter(new StandardGradientPainter());  //Render Settings. -ZL  
                             
                               SubstanceLookAndFeel.setCurrentTitlePainter(new MatteHeaderPainter()); //Set title. -ZL
  
    } catch (UnsupportedLookAndFeelException e) {  
        System.err.println("Something went wrong!");  
    }  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSponsors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewSponsorsAddButton;
    private javax.swing.JButton viewSponsorsBackButton;
    private javax.swing.JButton viewSponsorsDeleteButton;
    private javax.swing.JList<String> viewSponsorsJlist;
    private javax.swing.JLabel viewSponsorsLabel;
    private javax.swing.JLabel viewSponsorsLogoLabel;
    // End of variables declaration//GEN-END:variables
}
